[package]
name = "emote"
version = "0.1.0"
edition = "2021"

[dependencies]
display-interface-spi = "0.5.0"
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
rppal = { version = "0.22.1", features = ["embedded-hal"] }
ssd1309 = {path = "./lib/ssd1309"}
